// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverInternal.proto

#ifndef PROTOBUF_serverInternal_2eproto__INCLUDED
#define PROTOBUF_serverInternal_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "options.pb.h"
// @@protoc_insertion_point(includes)

namespace protoc {
namespace serverInternal {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_serverInternal_2eproto();
void protobuf_AssignDesc_serverInternal_2eproto();
void protobuf_ShutdownFile_serverInternal_2eproto();

class NineOneLoginAuthReq;
class NineOneLoginAuthAck;

// ===================================================================

class NineOneLoginAuthReq : public ::google::protobuf::Message {
 public:
  NineOneLoginAuthReq();
  virtual ~NineOneLoginAuthReq();
  
  NineOneLoginAuthReq(const NineOneLoginAuthReq& from);
  
  inline NineOneLoginAuthReq& operator=(const NineOneLoginAuthReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const NineOneLoginAuthReq& default_instance();
  
  void Swap(NineOneLoginAuthReq* other);
  
  // implements Message ----------------------------------------------
  
  NineOneLoginAuthReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NineOneLoginAuthReq& from);
  void MergeFrom(const NineOneLoginAuthReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string Uin = 1;
  inline bool has_uin() const;
  inline void clear_uin();
  static const int kUinFieldNumber = 1;
  inline const ::std::string& uin() const;
  inline void set_uin(const ::std::string& value);
  inline void set_uin(const char* value);
  inline void set_uin(const char* value, size_t size);
  inline ::std::string* mutable_uin();
  inline ::std::string* release_uin();
  
  // required string SessionId = 2;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 2;
  inline const ::std::string& sessionid() const;
  inline void set_sessionid(const ::std::string& value);
  inline void set_sessionid(const char* value);
  inline void set_sessionid(const char* value, size_t size);
  inline ::std::string* mutable_sessionid();
  inline ::std::string* release_sessionid();
  
  // @@protoc_insertion_point(class_scope:protoc.serverInternal.NineOneLoginAuthReq)
 private:
  inline void set_has_uin();
  inline void clear_has_uin();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* uin_;
  ::std::string* sessionid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_serverInternal_2eproto();
  friend void protobuf_AssignDesc_serverInternal_2eproto();
  friend void protobuf_ShutdownFile_serverInternal_2eproto();
  
  void InitAsDefaultInstance();
  static NineOneLoginAuthReq* default_instance_;
};
// -------------------------------------------------------------------

class NineOneLoginAuthAck : public ::google::protobuf::Message {
 public:
  NineOneLoginAuthAck();
  virtual ~NineOneLoginAuthAck();
  
  NineOneLoginAuthAck(const NineOneLoginAuthAck& from);
  
  inline NineOneLoginAuthAck& operator=(const NineOneLoginAuthAck& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const NineOneLoginAuthAck& default_instance();
  
  void Swap(NineOneLoginAuthAck* other);
  
  // implements Message ----------------------------------------------
  
  NineOneLoginAuthAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NineOneLoginAuthAck& from);
  void MergeFrom(const NineOneLoginAuthAck& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 ErrorCode = 1;
  inline bool has_errorcode() const;
  inline void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 errorcode() const;
  inline void set_errorcode(::google::protobuf::int32 value);
  
  // required string ErrorDesc = 2;
  inline bool has_errordesc() const;
  inline void clear_errordesc();
  static const int kErrorDescFieldNumber = 2;
  inline const ::std::string& errordesc() const;
  inline void set_errordesc(const ::std::string& value);
  inline void set_errordesc(const char* value);
  inline void set_errordesc(const char* value, size_t size);
  inline ::std::string* mutable_errordesc();
  inline ::std::string* release_errordesc();
  
  // @@protoc_insertion_point(class_scope:protoc.serverInternal.NineOneLoginAuthAck)
 private:
  inline void set_has_errorcode();
  inline void clear_has_errorcode();
  inline void set_has_errordesc();
  inline void clear_has_errordesc();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* errordesc_;
  ::google::protobuf::int32 errorcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_serverInternal_2eproto();
  friend void protobuf_AssignDesc_serverInternal_2eproto();
  friend void protobuf_ShutdownFile_serverInternal_2eproto();
  
  void InitAsDefaultInstance();
  static NineOneLoginAuthAck* default_instance_;
};
// ===================================================================


// ===================================================================

// NineOneLoginAuthReq

// required string Uin = 1;
inline bool NineOneLoginAuthReq::has_uin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NineOneLoginAuthReq::set_has_uin() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NineOneLoginAuthReq::clear_has_uin() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NineOneLoginAuthReq::clear_uin() {
  if (uin_ != &::google::protobuf::internal::kEmptyString) {
    uin_->clear();
  }
  clear_has_uin();
}
inline const ::std::string& NineOneLoginAuthReq::uin() const {
  return *uin_;
}
inline void NineOneLoginAuthReq::set_uin(const ::std::string& value) {
  set_has_uin();
  if (uin_ == &::google::protobuf::internal::kEmptyString) {
    uin_ = new ::std::string;
  }
  uin_->assign(value);
}
inline void NineOneLoginAuthReq::set_uin(const char* value) {
  set_has_uin();
  if (uin_ == &::google::protobuf::internal::kEmptyString) {
    uin_ = new ::std::string;
  }
  uin_->assign(value);
}
inline void NineOneLoginAuthReq::set_uin(const char* value, size_t size) {
  set_has_uin();
  if (uin_ == &::google::protobuf::internal::kEmptyString) {
    uin_ = new ::std::string;
  }
  uin_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NineOneLoginAuthReq::mutable_uin() {
  set_has_uin();
  if (uin_ == &::google::protobuf::internal::kEmptyString) {
    uin_ = new ::std::string;
  }
  return uin_;
}
inline ::std::string* NineOneLoginAuthReq::release_uin() {
  clear_has_uin();
  if (uin_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = uin_;
    uin_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string SessionId = 2;
inline bool NineOneLoginAuthReq::has_sessionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NineOneLoginAuthReq::set_has_sessionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NineOneLoginAuthReq::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NineOneLoginAuthReq::clear_sessionid() {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    sessionid_->clear();
  }
  clear_has_sessionid();
}
inline const ::std::string& NineOneLoginAuthReq::sessionid() const {
  return *sessionid_;
}
inline void NineOneLoginAuthReq::set_sessionid(const ::std::string& value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void NineOneLoginAuthReq::set_sessionid(const char* value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void NineOneLoginAuthReq::set_sessionid(const char* value, size_t size) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NineOneLoginAuthReq::mutable_sessionid() {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  return sessionid_;
}
inline ::std::string* NineOneLoginAuthReq::release_sessionid() {
  clear_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sessionid_;
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// NineOneLoginAuthAck

// required int32 ErrorCode = 1;
inline bool NineOneLoginAuthAck::has_errorcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NineOneLoginAuthAck::set_has_errorcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NineOneLoginAuthAck::clear_has_errorcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NineOneLoginAuthAck::clear_errorcode() {
  errorcode_ = 0;
  clear_has_errorcode();
}
inline ::google::protobuf::int32 NineOneLoginAuthAck::errorcode() const {
  return errorcode_;
}
inline void NineOneLoginAuthAck::set_errorcode(::google::protobuf::int32 value) {
  set_has_errorcode();
  errorcode_ = value;
}

// required string ErrorDesc = 2;
inline bool NineOneLoginAuthAck::has_errordesc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NineOneLoginAuthAck::set_has_errordesc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NineOneLoginAuthAck::clear_has_errordesc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NineOneLoginAuthAck::clear_errordesc() {
  if (errordesc_ != &::google::protobuf::internal::kEmptyString) {
    errordesc_->clear();
  }
  clear_has_errordesc();
}
inline const ::std::string& NineOneLoginAuthAck::errordesc() const {
  return *errordesc_;
}
inline void NineOneLoginAuthAck::set_errordesc(const ::std::string& value) {
  set_has_errordesc();
  if (errordesc_ == &::google::protobuf::internal::kEmptyString) {
    errordesc_ = new ::std::string;
  }
  errordesc_->assign(value);
}
inline void NineOneLoginAuthAck::set_errordesc(const char* value) {
  set_has_errordesc();
  if (errordesc_ == &::google::protobuf::internal::kEmptyString) {
    errordesc_ = new ::std::string;
  }
  errordesc_->assign(value);
}
inline void NineOneLoginAuthAck::set_errordesc(const char* value, size_t size) {
  set_has_errordesc();
  if (errordesc_ == &::google::protobuf::internal::kEmptyString) {
    errordesc_ = new ::std::string;
  }
  errordesc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NineOneLoginAuthAck::mutable_errordesc() {
  set_has_errordesc();
  if (errordesc_ == &::google::protobuf::internal::kEmptyString) {
    errordesc_ = new ::std::string;
  }
  return errordesc_;
}
inline ::std::string* NineOneLoginAuthAck::release_errordesc() {
  clear_has_errordesc();
  if (errordesc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = errordesc_;
    errordesc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace serverInternal
}  // namespace protoc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_serverInternal_2eproto__INCLUDED
